name: barcode_inventory_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: 
   git:
    url: https://github.com/irawanmurjayanto/barcode_modi2.git      
  flutter_easyloading: ^3.0.5
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  pdf: ^3.11.0 
  printing: ^5.4.2
  data_table_2: ^2.5.15
  path_provider: ^2.1.3
  flutter_inappwebview: ^5.8.0
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^4.8.0
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  screenshot: ^2.5.0
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdf: ^26.2.7
  flutter_pdfview: ^1.3.2
  get_storage: ^2.1.1
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  connectivity_plus: ^6.0.4
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    

